### ISSUE TITLE
2.4 Feature List

### ISSUE THREAD

**Issue by AnEmortalKid** [dogescript/dogescript#114]
Placeholder to link all the other currently open issues planned for 2.4 that existed pre-revive.

- [x] Documentation Updates #86 
- [x] Anonymous function support #87 
- [x] Deprecate `truedoge` mode #85 
  - [x] Also deprecate from plugins
- [x] throw/try/catch/finally #76 *consider keywords*
- [x] typeof and instanceof #75 
- [x] commonJS module.exports keyword #73 
- [x] debugger support #74  (replace with `pawse`)
- [x] `array levl 1` => `array[1]` , `ary is pack` -> `ary = []` , `pares` -> obj definition. Also `from` or something to do `obj.prop`, maybe gimme or giv `obj gimme prop` `obj giv prop`. #35 
- [x] possible ambiguity reduction: #45  `is` => `same` and maybe `also`
- [x] Class/Extends support #126 
- [x] do/while support
- [x] Expression support in IF statements (i.e `very Math dose random bigger 3`)
- [x] Info on syntax errors (line / token) instead of just throwing them.
- [x] `break` keyword

**Comment by AnEmortalKid** [comment]
#87 already existed (verified in #104 since we had to backtrack).

**Comment by AnEmortalKid** [comment]
For #45 , I think i'd like to rename the comparison `is` to `same`:

```dogescript

very foo is 'wow'
very bar is 'wow'
rly foo same bar
console dose loge with 'wowser'
but
console dose loge with 'sad'
wow

```

**Comment by AnEmortalKid** [comment]
Looking at ECMA 5 support: (keywords) https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar

for `class`, `extends`, `super`:

```
classy Polygon very Shape
  such constructor with name
    sooper with name
  wow
wow
```

=>
```
class Polygon extends Shape {

constructor(name) {
  super(name);
}

}
```

**Comment by vpzomtrrfrt** [comment]
super should probably still use `plz`.  Since so is already used for imports, I'd lean toward classy between those two options

**Comment by AnEmortalKid** [comment]
Since `very` is already variable declaration (and our parser is a bit messy), what about:

```
classy Polygon leads Shape
  such constructor much name
    plz sooper with name
  wow
wow
```

so:

`classy` -> `class`
`leads` -> `extends`, I was trying to make a pun on leash, like `classy blah drags blah` or `classy blah leash blah`
`sooper` -> `super`

**Comment by vpzomtrrfrt** [comment]
Leads seems like it would imply the other direction

**Comment by AnEmortalKid** [comment]
Ah, I didn't see it that way:

`Polygon <- Shape`, maybe `xtends` ?

**Comment by Purpzie** [comment]
I would definitely prefer `giv` over `gimme` to be honest, just since it's shorter. Perhaps it could support both, though, if people can't decide.

**Comment by AnEmortalKid** [comment]
> I would definitely prefer giv over gimme to be honest, just since it's shorter. Perhaps it could support both, though, if people can't decide.

Let's go with `giv` first and adding `gimme` later should be fairly easy

**Comment by AnEmortalKid** [comment]
Fixed #73 with #131

**Comment by AnEmortalKid** [comment]
Property accessors in #35 fixed with #192 #197

**Comment by AnEmortalKid** [comment]
```
=== -> same
== -> like
```

based on: 
> JavaScript has both strict and type–converting comparisons. A strict comparison (e.g., ===) is only true if the operands are of the same type and the contents match. The more commonly-used abstract comparison (e.g. ==) converts the operands to the same type before making the comparison. For relational abstract comparisons (e.g., <=), the operands are first converted to primitives, then to the same type, before comparison.

**Comment by AnEmortalKid** [comment]
Both do/while and try/catch/finally require some better capturing of state. The state tracking mechanisms for 2.4.0 are limited, and at this point the re-write would handle these better.

**Comment by AnEmortalKid** [comment]
https://www.npmjs.com/package/grunt-dogescript/v/2.4.0
https://www.npmjs.com/package/dogescript-loader/v/2.4.0
https://www.npmjs.com/package/require-doge/v/2.4.0

This completes this issue :)  🥳
